name: regression
verbose: true
save_logs: true
seed: 42
output_dir: outputs

architecture:
    in_size: 9
    out_size: 3
    hidden_layers: [64, 32]
    activation: ReLU
    use_dropout: true
    dropout: 0.5
    dropout_inplace: true
    final_activation: null

training:
    learning_rate: 0.001
    optimizer: Adam
    loss_function: MSELoss
    epochs: 100
    early_stopping: true
    patience: 10
    scheduler: ReduceLROnPlateau
    scheduler_patience: 5
    scheduler_factor: 0.5
    scheduler_threshold: 0.1

data:
    path_to_data: path
    num_samples: 5000
    batch_size: 5
    in_cols: [A11, A21, A31, A12, A22, A32, A13, A23, A33]
    out_cols: [B1, B2, B3]
    val_split: 0.1
    shuffle: false
    sliding_window: null
